### ISSUE TITLE
Initial download gets stuck at 100%

### ISSUE THREAD

**Issue by wjt** [endlessm/kolibri-explore-plugin#648]
Version: Ladybird 6.17-348
Platform: Android 13 (Google Pixel 7) but also seen on a Chromebook running an earlier incarnation of Android

Steps to reproduce:

- Clear app data
- Select a content pack, any content pack
- Wait for the progress bar to creep up to 100%

Expected result:

- Once the progress bar reaches 100%, the "Show Me" button appears

Actual result:

- The progress bar reaches 100% but no "Show Me" button appears
- The following backtrace appears in `adb logcat`:

```
django.request: Internal Server Error: /explore/api/ek-collections/update-download
Traceback (most recent call last):
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/django/views/generic/base.py", line 68, in view
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/rest_framework/views.py", line 495, in dispatch
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/rest_framework/views.py", line 492, in dispatch
  File "/home/jenkins/workspace/kolibri-installer-android/src/kolibri/dist/rest_framework/decorators.py", line 54, in handler
  File "/home/jenkins/workspace/kolibri-installer-android/_cache/.local/share/python-for-android/build/python-installs/kolibri/arm64-v8a/kolibri_explore_plugin/collectionviews.py", line 784, in update_download
  File "/home/jenkins/workspace/kolibri-installer-android/_cache/.local/share/python-for-android/build/python-installs/kolibri/arm64-v8a/kolibri_explore_plugin/collectionviews.py", line 389, in update
  File "/home/jenkins/workspace/kolibri-installer-android/_cache/.local/share/python-for-android/build/python-installs/kolibri/arm64-v8a/kolibri_explore_plugin/collectionviews.py", line 503, in _next_task_or_stage
  File "/home/jenkins/workspace/kolibri-installer-android/_cache/.local/share/python-for-android/build/python-installs/kolibri/arm64-v8a/kolibri_explore_plugin/collectionviews.py", line 528, in _set_next_stage
  File "/home/jenkins/workspace/kolibri-installer-android/_cache/.local/share/python-for-android/build/python-installs/kolibri/arm64-v8a/kolibri_explore_plugin/collectionviews.py", line 199, in get_contentthumbnail_tasks
AttributeError: 'EndlessKeyContentManifest' object has no attribute '_get_channel_metadata'
cherrypy.access: 127.0.0.1 - - "POST /explore/api/ek-collections/update-download" 500 0 "http://127.0.0.1:40933/en/explore/" "Mozilla/5.0 (Linux; Human 13; Pixel 7 Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko)  Chrome/114.0.5735.131 Mobile Safari/537.36"
```

If I switch to another app and back again, the app reaches the "Show Me" stage when it resumes:

```
06-20 18:08:41.047 11014 12618 I org.endlessos.Key: kolibri_explore_plugin.collectionviews: Started download stage: COMPLETED
```

[oh-no.txt](https://github.com/endlessm/kolibri-explore-plugin/files/11808043/oh-no.txt)

**Comment by dylanmccall** [comment]
Oh, this is a quick fix. I'll make a pull request for this in a moment.

**Comment by manuq** [comment]
I'll make sure to test a full download before releasing next time.
